version: '3.8'

services:
  analytics-ui:
    build: .
    container_name: analytics-ui
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://leads.photowaermo.de/analytics
    networks:
      - gateway_net

networks:
  gateway_net:
    external: true
